name: Production Release

#on:
#  create:
#    tags:
#      - 'production_**'
on:
  release:
    types: [prereleased,published,edited]

jobs:
  deploy:
    uses: alekkol/consul-client/.github/workflows/deploy.yml
    with:
      some_input: 'custom input to use in workflow'
      environment: production
    secrets:
      SOME_SECRET: '${{ secrets.SOME_SECRET }}'

  finish:
    runs-on: ubuntu-latest
    needs: [ deploy ]

    steps:
      - name: Finish output
        shell: bash
        run: |
          echo Deploy workflow has been finished
