name: Deploy OPA builds to S3

on:
  workflow_call:
    inputs:
      some_input:
        description: 'Input to test reusable workflow'
        required: true
        type: string
        default: 'this is default input value'
      environment:
        description: 'Environment to run workflow'
        required: true
        type: string
        default: 'staging'
    secrets:
      SOME_SECRET:
        description: 'Some secret to test repository/environment secrets'
        required: true

env:
  SOME_SECRET: "${{ secrets.SOME_SECRET }}"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NOT_A_SECRET: ${{ secrets.SOME_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 13.0
        uses: actions/setup-java@v1
        with:
          java-version: 13.0

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Debug output
        shell: bash
        run: |
          echo inputs.some_input = ${{ inputs.some_input }}
          echo secrets.SOME_SECRET length = ${#NOT_A_SECRET}